name: 'Test Compare Versions'

on:
  push:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  test-compare-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Full Equality
      id: full_equality
      uses: './'
      with:
        source-version: 'v1.0.0'
        target-version: 'v1.0.0'

    - name: Print Full Equality Results
      run: |
        echo "Full Equality: ${{ env.VERSION_EQUALITY }}"
        echo "Versions Are Equal: ${{ env.VERSIONS_ARE_EQUAL }}"

    - name: Test Partial Equality
      id: partial_equality
      uses: './'
      with:
        source-version: 'v1.0.0'
        target-version: 'v1.0.0-alpha'

    - name: Print Partial Equality Results
      run: |
        echo "Partial Equality: ${{ env.VERSION_EQUALITY }}"
        echo "Versions Are Equal: ${{ env.VERSIONS_ARE_EQUAL }}"
        if [ "${{ env.VERSIONS_ARE_EQUAL }}" == "false" ]; then
          echo "Highest Version: ${{ env.HIGHEST_VERSION }}"
        fi

    - name: Test No Equality
      id: no_equality
      uses: './'
      with:
        source-version: 'v1.0.0'
        target-version: 'v2.0.0'

    - name: Print No Equality Results
      run: |
        echo "No Equality: ${{ env.VERSION_EQUALITY }}"
        echo "Versions Are Equal: ${{ env.VERSIONS_ARE_EQUAL }}"
        if [ "${{ env.VERSIONS_ARE_EQUAL }}" == "false" ]; then
          echo "Highest Version: ${{ env.HIGHEST_VERSION }}"
        fi
